---
# This workflow will install Python dependencies
# and run unit tests for given OSes

name: Unit tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-latest'
            python-version: '3.7'
            rf-version: '3.2.2'
          - os: 'ubuntu-latest'
            python-version: '3.8'
            rf-version: '4.1.3'
          - os: 'ubuntu-latest'
            python-version: '3.9'
            rf-version: '5.0.1'
          - os: 'ubuntu-latest'
            python-version: '3.10'
            rf-version: '6.1.1'
          - os: 'ubuntu-latest'
            python-version: '3.11'
            rf-version: '6.1.1'
          - os: 'ubuntu-latest'
            python-version: '3.12'
            rf-version: '7.0a1'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework==${{ matrix.rf-version }} coverage pytest
          pip install .

      - name: Run unit tests with coverage
        run:
          coverage run -m pytest

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          name: ${{ matrix.python-version }}-${{ matrix.os }}-${{ matrix.rf-version }}
